using System.Drawing;
using System.Windows.Forms;

namespace DoAn
{
    partial class FrmOrder_Add
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmOrder_Add));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuDragControl1 = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.pnlMain = new Bunifu.UI.WinForms.BunifuPanel();
            this.lblStockInfo = new Bunifu.UI.WinForms.BunifuLabel();
            this.BtnHienThi = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.btnCancel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblPrice = new Bunifu.UI.WinForms.BunifuLabel();
            this.COGs = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.Status = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtSKU = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblSKU = new Bunifu.UI.WinForms.BunifuLabel();
            this.numImportCost = new Bunifu.UI.WinForms.BunifuTextBox();
            this.numPrice = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtOrderID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSoLuong = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTrangThaiSanPham = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lblProductName = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblTitle = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.pnlMain.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 15;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuDragControl1
            // 
            this.bunifuDragControl1.Fixed = true;
            this.bunifuDragControl1.Horizontal = true;
            this.bunifuDragControl1.TargetControl = this.pnlMain;
            this.bunifuDragControl1.Vertical = true;
            // 
            // pnlMain
            // 
            this.pnlMain.BackgroundColor = System.Drawing.Color.White;
            this.pnlMain.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("pnlMain.BackgroundImage")));
            this.pnlMain.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.pnlMain.BorderColor = System.Drawing.Color.Gainsboro;
            this.pnlMain.BorderRadius = 15;
            this.pnlMain.BorderThickness = 1;
            this.pnlMain.Controls.Add(this.lblStockInfo);
            this.pnlMain.Controls.Add(this.BtnHienThi);
            this.pnlMain.Controls.Add(this.bunifuSeparator1);
            this.pnlMain.Controls.Add(this.btnCancel);
            this.pnlMain.Controls.Add(this.btnSave);
            this.pnlMain.Controls.Add(this.lblPrice);
            this.pnlMain.Controls.Add(this.COGs);
            this.pnlMain.Controls.Add(this.bunifuLabel1);
            this.pnlMain.Controls.Add(this.Status);
            this.pnlMain.Controls.Add(this.txtSKU);
            this.pnlMain.Controls.Add(this.lblSKU);
            this.pnlMain.Controls.Add(this.numImportCost);
            this.pnlMain.Controls.Add(this.numPrice);
            this.pnlMain.Controls.Add(this.txtOrderID);
            this.pnlMain.Controls.Add(this.txtSoLuong);
            this.pnlMain.Controls.Add(this.txtTrangThaiSanPham);
            this.pnlMain.Controls.Add(this.txtName);
            this.pnlMain.Controls.Add(this.lblProductName);
            this.pnlMain.Controls.Add(this.lblTitle);
            this.pnlMain.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlMain.Location = new System.Drawing.Point(0, 0);
            this.pnlMain.Margin = new System.Windows.Forms.Padding(20, 18, 20, 18);
            this.pnlMain.Name = "pnlMain";
            this.pnlMain.Padding = new System.Windows.Forms.Padding(27, 25, 27, 25);
            this.pnlMain.ShowBorders = true;
            this.pnlMain.Size = new System.Drawing.Size(1315, 726);
            this.pnlMain.TabIndex = 0;
            // 
            // lblStockInfo
            // 
            this.lblStockInfo.AllowParentOverrides = false;
            this.lblStockInfo.AutoEllipsis = false;
            this.lblStockInfo.AutoSize = false;
            this.lblStockInfo.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblStockInfo.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblStockInfo.Font = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblStockInfo.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblStockInfo.Location = new System.Drawing.Point(520, 278);
            this.lblStockInfo.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.lblStockInfo.Name = "lblStockInfo";
            this.lblStockInfo.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblStockInfo.Size = new System.Drawing.Size(116, 28);
            this.lblStockInfo.TabIndex = 15;
            this.lblStockInfo.Text = "Số Lượng Tồn";
            this.lblStockInfo.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblStockInfo.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // BtnHienThi
            // 
            this.BtnHienThi.AllowAnimations = true;
            this.BtnHienThi.AllowMouseEffects = true;
            this.BtnHienThi.AllowToggling = false;
            this.BtnHienThi.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.BtnHienThi.AnimationSpeed = 200;
            this.BtnHienThi.AutoGenerateColors = false;
            this.BtnHienThi.AutoRoundBorders = false;
            this.BtnHienThi.AutoSizeLeftIcon = true;
            this.BtnHienThi.AutoSizeRightIcon = true;
            this.BtnHienThi.BackColor = System.Drawing.Color.Transparent;
            this.BtnHienThi.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.BtnHienThi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnHienThi.BackgroundImage")));
            this.BtnHienThi.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnHienThi.ButtonText = "Hiển Thị";
            this.BtnHienThi.ButtonTextMarginLeft = 0;
            this.BtnHienThi.ColorContrastOnClick = 45;
            this.BtnHienThi.ColorContrastOnHover = 45;
            this.BtnHienThi.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnHienThi.CustomizableEdges = borderEdges3;
            this.BtnHienThi.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnHienThi.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnHienThi.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnHienThi.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnHienThi.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnHienThi.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnHienThi.ForeColor = System.Drawing.Color.White;
            this.BtnHienThi.IconLeft = null;
            this.BtnHienThi.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnHienThi.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnHienThi.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnHienThi.IconMarginLeft = 11;
            this.BtnHienThi.IconPadding = 10;
            this.BtnHienThi.IconRight = null;
            this.BtnHienThi.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnHienThi.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnHienThi.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnHienThi.IconSize = 25;
            this.BtnHienThi.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.BtnHienThi.IdleBorderRadius = 8;
            this.BtnHienThi.IdleBorderThickness = 1;
            this.BtnHienThi.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.BtnHienThi.IdleIconLeftImage = null;
            this.BtnHienThi.IdleIconRightImage = null;
            this.BtnHienThi.IndicateFocus = false;
            this.BtnHienThi.Location = new System.Drawing.Point(744, 182);
            this.BtnHienThi.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.BtnHienThi.Name = "BtnHienThi";
            this.BtnHienThi.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnHienThi.OnDisabledState.BorderRadius = 39;
            this.BtnHienThi.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnHienThi.OnDisabledState.BorderThickness = 1;
            this.BtnHienThi.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnHienThi.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnHienThi.OnDisabledState.IconLeftImage = null;
            this.BtnHienThi.OnDisabledState.IconRightImage = null;
            this.BtnHienThi.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(70)))), ((int)(((byte)(80)))));
            this.BtnHienThi.onHoverState.BorderRadius = 39;
            this.BtnHienThi.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnHienThi.onHoverState.BorderThickness = 1;
            this.BtnHienThi.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(70)))), ((int)(((byte)(80)))));
            this.BtnHienThi.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnHienThi.onHoverState.IconLeftImage = null;
            this.BtnHienThi.onHoverState.IconRightImage = null;
            this.BtnHienThi.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.BtnHienThi.OnIdleState.BorderRadius = 39;
            this.BtnHienThi.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnHienThi.OnIdleState.BorderThickness = 1;
            this.BtnHienThi.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.BtnHienThi.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnHienThi.OnIdleState.IconLeftImage = null;
            this.BtnHienThi.OnIdleState.IconRightImage = null;
            this.BtnHienThi.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnHienThi.OnPressedState.BorderRadius = 39;
            this.BtnHienThi.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnHienThi.OnPressedState.BorderThickness = 1;
            this.BtnHienThi.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnHienThi.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnHienThi.OnPressedState.IconLeftImage = null;
            this.BtnHienThi.OnPressedState.IconRightImage = null;
            this.BtnHienThi.Size = new System.Drawing.Size(92, 48);
            this.BtnHienThi.TabIndex = 14;
            this.BtnHienThi.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnHienThi.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnHienThi.TextMarginLeft = 0;
            this.BtnHienThi.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnHienThi.UseDefaultRadiusAndThickness = true;
            this.BtnHienThi.Click += new System.EventHandler(this.BtnHienThi_Click);
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.Gainsboro;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 1;
            this.bunifuSeparator1.Location = new System.Drawing.Point(48, 580);
            this.bunifuSeparator1.Margin = new System.Windows.Forms.Padding(5, 5, 5, 5);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(1235, 23);
            this.bunifuSeparator1.TabIndex = 13;
            // 
            // btnCancel
            // 
            this.btnCancel.AllowAnimations = true;
            this.btnCancel.AllowMouseEffects = true;
            this.btnCancel.AllowToggling = false;
            this.btnCancel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnCancel.AnimationSpeed = 200;
            this.btnCancel.AutoGenerateColors = false;
            this.btnCancel.AutoRoundBorders = false;
            this.btnCancel.AutoSizeLeftIcon = true;
            this.btnCancel.AutoSizeRightIcon = true;
            this.btnCancel.BackColor = System.Drawing.Color.Transparent;
            this.btnCancel.BackColor1 = System.Drawing.Color.White;
            this.btnCancel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCancel.BackgroundImage")));
            this.btnCancel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.ButtonText = "Cancel";
            this.btnCancel.ButtonTextMarginLeft = 0;
            this.btnCancel.ColorContrastOnClick = 45;
            this.btnCancel.ColorContrastOnHover = 45;
            this.btnCancel.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCancel.CustomizableEdges = borderEdges2;
            this.btnCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnCancel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCancel.Font = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCancel.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnCancel.IconLeft = null;
            this.btnCancel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCancel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCancel.IconMarginLeft = 11;
            this.btnCancel.IconPadding = 10;
            this.btnCancel.IconRight = null;
            this.btnCancel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCancel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCancel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCancel.IconSize = 25;
            this.btnCancel.IdleBorderColor = System.Drawing.Color.Silver;
            this.btnCancel.IdleBorderRadius = 8;
            this.btnCancel.IdleBorderThickness = 1;
            this.btnCancel.IdleFillColor = System.Drawing.Color.White;
            this.btnCancel.IdleIconLeftImage = null;
            this.btnCancel.IdleIconRightImage = null;
            this.btnCancel.IndicateFocus = false;
            this.btnCancel.Location = new System.Drawing.Point(119, 638);
            this.btnCancel.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCancel.OnDisabledState.BorderRadius = 39;
            this.btnCancel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnDisabledState.BorderThickness = 1;
            this.btnCancel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCancel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCancel.OnDisabledState.IconLeftImage = null;
            this.btnCancel.OnDisabledState.IconRightImage = null;
            this.btnCancel.onHoverState.BorderColor = System.Drawing.Color.Gray;
            this.btnCancel.onHoverState.BorderRadius = 39;
            this.btnCancel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.onHoverState.BorderThickness = 1;
            this.btnCancel.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.btnCancel.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnCancel.onHoverState.IconLeftImage = null;
            this.btnCancel.onHoverState.IconRightImage = null;
            this.btnCancel.OnIdleState.BorderColor = System.Drawing.Color.Silver;
            this.btnCancel.OnIdleState.BorderRadius = 39;
            this.btnCancel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnIdleState.BorderThickness = 1;
            this.btnCancel.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnCancel.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.btnCancel.OnIdleState.IconLeftImage = null;
            this.btnCancel.OnIdleState.IconRightImage = null;
            this.btnCancel.OnPressedState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnCancel.OnPressedState.BorderRadius = 39;
            this.btnCancel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCancel.OnPressedState.BorderThickness = 1;
            this.btnCancel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.btnCancel.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnCancel.OnPressedState.IconLeftImage = null;
            this.btnCancel.OnPressedState.IconRightImage = null;
            this.btnCancel.Size = new System.Drawing.Size(160, 48);
            this.btnCancel.TabIndex = 6;
            this.btnCancel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCancel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCancel.TextMarginLeft = 0;
            this.btnCancel.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCancel.UseDefaultRadiusAndThickness = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges1;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeft = null;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRight = null;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.btnSave.IdleBorderRadius = 8;
            this.btnSave.IdleBorderThickness = 1;
            this.btnSave.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(1024, 638);
            this.btnSave.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 39;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(70)))), ((int)(((byte)(80)))));
            this.btnSave.onHoverState.BorderRadius = 39;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(60)))), ((int)(((byte)(70)))), ((int)(((byte)(80)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.btnSave.OnIdleState.BorderRadius = 39;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.BorderRadius = 39;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(160, 48);
            this.btnSave.TabIndex = 5;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // lblPrice
            // 
            this.lblPrice.AllowParentOverrides = false;
            this.lblPrice.AutoEllipsis = false;
            this.lblPrice.AutoSize = false;
            this.lblPrice.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblPrice.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblPrice.Font = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblPrice.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblPrice.Location = new System.Drawing.Point(520, 390);
            this.lblPrice.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.lblPrice.Name = "lblPrice";
            this.lblPrice.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblPrice.Size = new System.Drawing.Size(28, 28);
            this.lblPrice.TabIndex = 9;
            this.lblPrice.Text = "Giá";
            this.lblPrice.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblPrice.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // COGs
            // 
            this.COGs.AllowParentOverrides = false;
            this.COGs.AutoEllipsis = false;
            this.COGs.AutoSize = false;
            this.COGs.Cursor = System.Windows.Forms.Cursors.Default;
            this.COGs.CursorType = System.Windows.Forms.Cursors.Default;
            this.COGs.Font = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.COGs.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.COGs.Location = new System.Drawing.Point(119, 390);
            this.COGs.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.COGs.Name = "COGs";
            this.COGs.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.COGs.Size = new System.Drawing.Size(49, 28);
            this.COGs.TabIndex = 5;
            this.COGs.Text = "COGS";
            this.COGs.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.COGs.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(939, 383);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(69, 28);
            this.bunifuLabel1.TabIndex = 5;
            this.bunifuLabel1.Text = "OrderID";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Status
            // 
            this.Status.AllowParentOverrides = false;
            this.Status.AutoEllipsis = false;
            this.Status.AutoSize = false;
            this.Status.Cursor = System.Windows.Forms.Cursors.Default;
            this.Status.CursorType = System.Windows.Forms.Cursors.Default;
            this.Status.Font = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Status.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.Status.Location = new System.Drawing.Point(937, 278);
            this.Status.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Status.Name = "Status";
            this.Status.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.Status.Size = new System.Drawing.Size(175, 28);
            this.Status.TabIndex = 5;
            this.Status.Text = "Trạng Thái Sản Phẩm";
            this.Status.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.Status.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtSKU
            // 
            this.txtSKU.AcceptsReturn = false;
            this.txtSKU.AcceptsTab = false;
            this.txtSKU.AnimationSpeed = 200;
            this.txtSKU.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSKU.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSKU.AutoSizeHeight = true;
            this.txtSKU.BackColor = System.Drawing.Color.Transparent;
            this.txtSKU.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSKU.BackgroundImage")));
            this.txtSKU.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.txtSKU.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSKU.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSKU.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSKU.BorderRadius = 12;
            this.txtSKU.BorderThickness = 1;
            this.txtSKU.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSKU.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSKU.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSKU.DefaultFont = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSKU.DefaultText = "";
            this.txtSKU.FillColor = System.Drawing.Color.White;
            this.txtSKU.HideSelection = true;
            this.txtSKU.IconLeft = null;
            this.txtSKU.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSKU.IconPadding = 10;
            this.txtSKU.IconRight = null;
            this.txtSKU.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSKU.Lines = new string[0];
            this.txtSKU.Location = new System.Drawing.Point(457, 186);
            this.txtSKU.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtSKU.MaxLength = 32767;
            this.txtSKU.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSKU.Modified = false;
            this.txtSKU.Multiline = false;
            this.txtSKU.Name = "txtSKU";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSKU.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSKU.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSKU.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSKU.OnIdleState = stateProperties4;
            this.txtSKU.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtSKU.PasswordChar = '\0';
            this.txtSKU.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSKU.PlaceholderText = "Nhập mã SKU";
            this.txtSKU.ReadOnly = false;
            this.txtSKU.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSKU.SelectedText = "";
            this.txtSKU.SelectionLength = 0;
            this.txtSKU.SelectionStart = 0;
            this.txtSKU.ShortcutsEnabled = true;
            this.txtSKU.Size = new System.Drawing.Size(248, 41);
            this.txtSKU.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSKU.TabIndex = 1;
            this.txtSKU.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSKU.TextMarginBottom = 0;
            this.txtSKU.TextMarginLeft = 3;
            this.txtSKU.TextMarginTop = -2;
            this.txtSKU.TextPlaceholder = "Nhập mã SKU";
            this.txtSKU.UseSystemPasswordChar = false;
            this.txtSKU.WordWrap = true;
            this.txtSKU.TextChanged += new System.EventHandler(this.txtSKU_TextChanged);
            this.txtSKU.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtSKU_KeyDown);
            // 
            // lblSKU
            // 
            this.lblSKU.AllowParentOverrides = false;
            this.lblSKU.AutoEllipsis = false;
            this.lblSKU.AutoSize = false;
            this.lblSKU.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblSKU.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblSKU.Font = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblSKU.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblSKU.Location = new System.Drawing.Point(457, 150);
            this.lblSKU.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.lblSKU.Name = "lblSKU";
            this.lblSKU.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblSKU.Size = new System.Drawing.Size(37, 28);
            this.lblSKU.TabIndex = 3;
            this.lblSKU.Text = "SKU";
            this.lblSKU.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblSKU.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // numImportCost
            // 
            this.numImportCost.AcceptsReturn = false;
            this.numImportCost.AcceptsTab = false;
            this.numImportCost.AnimationSpeed = 200;
            this.numImportCost.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.numImportCost.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.numImportCost.AutoSizeHeight = true;
            this.numImportCost.BackColor = System.Drawing.Color.Transparent;
            this.numImportCost.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("numImportCost.BackgroundImage")));
            this.numImportCost.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.numImportCost.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.numImportCost.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.numImportCost.BorderColorIdle = System.Drawing.Color.Silver;
            this.numImportCost.BorderRadius = 12;
            this.numImportCost.BorderThickness = 1;
            this.numImportCost.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.numImportCost.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.numImportCost.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.numImportCost.DefaultFont = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.numImportCost.DefaultText = "";
            this.numImportCost.FillColor = System.Drawing.Color.White;
            this.numImportCost.HideSelection = true;
            this.numImportCost.IconLeft = null;
            this.numImportCost.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.numImportCost.IconPadding = 10;
            this.numImportCost.IconRight = null;
            this.numImportCost.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.numImportCost.Lines = new string[0];
            this.numImportCost.Location = new System.Drawing.Point(119, 420);
            this.numImportCost.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.numImportCost.MaxLength = 32767;
            this.numImportCost.MinimumSize = new System.Drawing.Size(1, 1);
            this.numImportCost.Modified = false;
            this.numImportCost.Multiline = false;
            this.numImportCost.Name = "numImportCost";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numImportCost.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.numImportCost.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numImportCost.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numImportCost.OnIdleState = stateProperties8;
            this.numImportCost.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.numImportCost.PasswordChar = '\0';
            this.numImportCost.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.numImportCost.PlaceholderText = "Cost Of Goods Sold";
            this.numImportCost.ReadOnly = true;
            this.numImportCost.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.numImportCost.SelectedText = "";
            this.numImportCost.SelectionLength = 0;
            this.numImportCost.SelectionStart = 0;
            this.numImportCost.ShortcutsEnabled = true;
            this.numImportCost.Size = new System.Drawing.Size(248, 41);
            this.numImportCost.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.numImportCost.TabIndex = 0;
            this.numImportCost.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.numImportCost.TextMarginBottom = 0;
            this.numImportCost.TextMarginLeft = 3;
            this.numImportCost.TextMarginTop = -3;
            this.numImportCost.TextPlaceholder = "Cost Of Goods Sold";
            this.numImportCost.UseSystemPasswordChar = false;
            this.numImportCost.WordWrap = true;
            // 
            // numPrice
            // 
            this.numPrice.AcceptsReturn = false;
            this.numPrice.AcceptsTab = false;
            this.numPrice.AnimationSpeed = 200;
            this.numPrice.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.numPrice.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.numPrice.AutoSizeHeight = true;
            this.numPrice.BackColor = System.Drawing.Color.Transparent;
            this.numPrice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("numPrice.BackgroundImage")));
            this.numPrice.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.numPrice.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.numPrice.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.numPrice.BorderColorIdle = System.Drawing.Color.Silver;
            this.numPrice.BorderRadius = 12;
            this.numPrice.BorderThickness = 1;
            this.numPrice.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.numPrice.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.numPrice.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.numPrice.DefaultFont = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.numPrice.DefaultText = "";
            this.numPrice.FillColor = System.Drawing.Color.White;
            this.numPrice.HideSelection = true;
            this.numPrice.IconLeft = null;
            this.numPrice.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.numPrice.IconPadding = 10;
            this.numPrice.IconRight = null;
            this.numPrice.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.numPrice.Lines = new string[0];
            this.numPrice.Location = new System.Drawing.Point(520, 420);
            this.numPrice.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.numPrice.MaxLength = 32767;
            this.numPrice.MinimumSize = new System.Drawing.Size(1, 1);
            this.numPrice.Modified = false;
            this.numPrice.Multiline = false;
            this.numPrice.Name = "numPrice";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numPrice.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.numPrice.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numPrice.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.numPrice.OnIdleState = stateProperties12;
            this.numPrice.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.numPrice.PasswordChar = '\0';
            this.numPrice.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.numPrice.PlaceholderText = "Giá bán";
            this.numPrice.ReadOnly = true;
            this.numPrice.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.numPrice.SelectedText = "";
            this.numPrice.SelectionLength = 0;
            this.numPrice.SelectionStart = 0;
            this.numPrice.ShortcutsEnabled = true;
            this.numPrice.Size = new System.Drawing.Size(248, 41);
            this.numPrice.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.numPrice.TabIndex = 0;
            this.numPrice.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.numPrice.TextMarginBottom = 0;
            this.numPrice.TextMarginLeft = 3;
            this.numPrice.TextMarginTop = -3;
            this.numPrice.TextPlaceholder = "Giá bán";
            this.numPrice.UseSystemPasswordChar = false;
            this.numPrice.WordWrap = true;
            // 
            // txtOrderID
            // 
            this.txtOrderID.AcceptsReturn = false;
            this.txtOrderID.AcceptsTab = false;
            this.txtOrderID.AnimationSpeed = 200;
            this.txtOrderID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtOrderID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtOrderID.AutoSizeHeight = true;
            this.txtOrderID.BackColor = System.Drawing.Color.Transparent;
            this.txtOrderID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtOrderID.BackgroundImage")));
            this.txtOrderID.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.txtOrderID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtOrderID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtOrderID.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtOrderID.BorderRadius = 12;
            this.txtOrderID.BorderThickness = 1;
            this.txtOrderID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtOrderID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtOrderID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrderID.DefaultFont = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtOrderID.DefaultText = "";
            this.txtOrderID.FillColor = System.Drawing.Color.White;
            this.txtOrderID.HideSelection = true;
            this.txtOrderID.IconLeft = null;
            this.txtOrderID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrderID.IconPadding = 10;
            this.txtOrderID.IconRight = null;
            this.txtOrderID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtOrderID.Lines = new string[0];
            this.txtOrderID.Location = new System.Drawing.Point(937, 412);
            this.txtOrderID.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtOrderID.MaxLength = 32767;
            this.txtOrderID.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtOrderID.Modified = false;
            this.txtOrderID.Multiline = false;
            this.txtOrderID.Name = "txtOrderID";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrderID.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtOrderID.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrderID.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtOrderID.OnIdleState = stateProperties16;
            this.txtOrderID.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtOrderID.PasswordChar = '\0';
            this.txtOrderID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtOrderID.PlaceholderText = "";
            this.txtOrderID.ReadOnly = false;
            this.txtOrderID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtOrderID.SelectedText = "";
            this.txtOrderID.SelectionLength = 0;
            this.txtOrderID.SelectionStart = 0;
            this.txtOrderID.ShortcutsEnabled = true;
            this.txtOrderID.Size = new System.Drawing.Size(248, 41);
            this.txtOrderID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtOrderID.TabIndex = 0;
            this.txtOrderID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtOrderID.TextMarginBottom = 0;
            this.txtOrderID.TextMarginLeft = 3;
            this.txtOrderID.TextMarginTop = -2;
            this.txtOrderID.TextPlaceholder = "";
            this.txtOrderID.UseSystemPasswordChar = false;
            this.txtOrderID.WordWrap = true;
            // 
            // txtSoLuong
            // 
            this.txtSoLuong.AcceptsReturn = false;
            this.txtSoLuong.AcceptsTab = false;
            this.txtSoLuong.AnimationSpeed = 200;
            this.txtSoLuong.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSoLuong.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSoLuong.AutoSizeHeight = true;
            this.txtSoLuong.BackColor = System.Drawing.Color.Transparent;
            this.txtSoLuong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSoLuong.BackgroundImage")));
            this.txtSoLuong.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.txtSoLuong.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSoLuong.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSoLuong.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSoLuong.BorderRadius = 12;
            this.txtSoLuong.BorderThickness = 1;
            this.txtSoLuong.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSoLuong.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSoLuong.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.DefaultFont = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSoLuong.DefaultText = "";
            this.txtSoLuong.FillColor = System.Drawing.Color.White;
            this.txtSoLuong.HideSelection = true;
            this.txtSoLuong.IconLeft = null;
            this.txtSoLuong.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.IconPadding = 10;
            this.txtSoLuong.IconRight = null;
            this.txtSoLuong.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSoLuong.Lines = new string[0];
            this.txtSoLuong.Location = new System.Drawing.Point(520, 308);
            this.txtSoLuong.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtSoLuong.MaxLength = 32767;
            this.txtSoLuong.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSoLuong.Modified = false;
            this.txtSoLuong.Multiline = false;
            this.txtSoLuong.Name = "txtSoLuong";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSoLuong.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSoLuong.OnIdleState = stateProperties20;
            this.txtSoLuong.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtSoLuong.PasswordChar = '\0';
            this.txtSoLuong.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSoLuong.PlaceholderText = "Số lương cần bán";
            this.txtSoLuong.ReadOnly = false;
            this.txtSoLuong.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSoLuong.SelectedText = "";
            this.txtSoLuong.SelectionLength = 0;
            this.txtSoLuong.SelectionStart = 0;
            this.txtSoLuong.ShortcutsEnabled = true;
            this.txtSoLuong.Size = new System.Drawing.Size(248, 41);
            this.txtSoLuong.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSoLuong.TabIndex = 0;
            this.txtSoLuong.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSoLuong.TextMarginBottom = 0;
            this.txtSoLuong.TextMarginLeft = 3;
            this.txtSoLuong.TextMarginTop = -3;
            this.txtSoLuong.TextPlaceholder = "Số lương cần bán";
            this.txtSoLuong.UseSystemPasswordChar = false;
            this.txtSoLuong.WordWrap = true;
            this.txtSoLuong.TextChanged += new System.EventHandler(this.txtTrangThaiSanPham_TextChanged);
            // 
            // txtTrangThaiSanPham
            // 
            this.txtTrangThaiSanPham.AcceptsReturn = false;
            this.txtTrangThaiSanPham.AcceptsTab = false;
            this.txtTrangThaiSanPham.AnimationSpeed = 200;
            this.txtTrangThaiSanPham.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTrangThaiSanPham.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTrangThaiSanPham.AutoSizeHeight = true;
            this.txtTrangThaiSanPham.BackColor = System.Drawing.Color.Transparent;
            this.txtTrangThaiSanPham.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTrangThaiSanPham.BackgroundImage")));
            this.txtTrangThaiSanPham.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.txtTrangThaiSanPham.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTrangThaiSanPham.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTrangThaiSanPham.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTrangThaiSanPham.BorderRadius = 12;
            this.txtTrangThaiSanPham.BorderThickness = 1;
            this.txtTrangThaiSanPham.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtTrangThaiSanPham.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTrangThaiSanPham.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTrangThaiSanPham.DefaultFont = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtTrangThaiSanPham.DefaultText = "";
            this.txtTrangThaiSanPham.FillColor = System.Drawing.Color.White;
            this.txtTrangThaiSanPham.HideSelection = true;
            this.txtTrangThaiSanPham.IconLeft = null;
            this.txtTrangThaiSanPham.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTrangThaiSanPham.IconPadding = 10;
            this.txtTrangThaiSanPham.IconRight = null;
            this.txtTrangThaiSanPham.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTrangThaiSanPham.Lines = new string[0];
            this.txtTrangThaiSanPham.Location = new System.Drawing.Point(936, 308);
            this.txtTrangThaiSanPham.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtTrangThaiSanPham.MaxLength = 32767;
            this.txtTrangThaiSanPham.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTrangThaiSanPham.Modified = false;
            this.txtTrangThaiSanPham.Multiline = false;
            this.txtTrangThaiSanPham.Name = "txtTrangThaiSanPham";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTrangThaiSanPham.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTrangThaiSanPham.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTrangThaiSanPham.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTrangThaiSanPham.OnIdleState = stateProperties24;
            this.txtTrangThaiSanPham.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtTrangThaiSanPham.PasswordChar = '\0';
            this.txtTrangThaiSanPham.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTrangThaiSanPham.PlaceholderText = "Trạng Thái sản phẩm";
            this.txtTrangThaiSanPham.ReadOnly = true;
            this.txtTrangThaiSanPham.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTrangThaiSanPham.SelectedText = "";
            this.txtTrangThaiSanPham.SelectionLength = 0;
            this.txtTrangThaiSanPham.SelectionStart = 0;
            this.txtTrangThaiSanPham.ShortcutsEnabled = true;
            this.txtTrangThaiSanPham.Size = new System.Drawing.Size(248, 41);
            this.txtTrangThaiSanPham.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTrangThaiSanPham.TabIndex = 0;
            this.txtTrangThaiSanPham.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTrangThaiSanPham.TextMarginBottom = 0;
            this.txtTrangThaiSanPham.TextMarginLeft = 3;
            this.txtTrangThaiSanPham.TextMarginTop = -3;
            this.txtTrangThaiSanPham.TextPlaceholder = "Trạng Thái sản phẩm";
            this.txtTrangThaiSanPham.UseSystemPasswordChar = false;
            this.txtTrangThaiSanPham.WordWrap = true;
            this.txtTrangThaiSanPham.TextChanged += new System.EventHandler(this.txtTrangThaiSanPham_TextChanged);
            // 
            // txtName
            // 
            this.txtName.AcceptsReturn = false;
            this.txtName.AcceptsTab = false;
            this.txtName.AnimationSpeed = 200;
            this.txtName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtName.AutoSizeHeight = true;
            this.txtName.BackColor = System.Drawing.Color.Transparent;
            this.txtName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtName.BackgroundImage")));
            this.txtName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.txtName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtName.BorderRadius = 12;
            this.txtName.BorderThickness = 1;
            this.txtName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.DefaultFont = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtName.DefaultText = "";
            this.txtName.FillColor = System.Drawing.Color.White;
            this.txtName.HideSelection = true;
            this.txtName.IconLeft = null;
            this.txtName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.IconPadding = 10;
            this.txtName.IconRight = null;
            this.txtName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtName.Lines = new string[0];
            this.txtName.Location = new System.Drawing.Point(119, 308);
            this.txtName.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtName.MaxLength = 32767;
            this.txtName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtName.Modified = false;
            this.txtName.Multiline = false;
            this.txtName.Name = "txtName";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtName.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtName.OnIdleState = stateProperties28;
            this.txtName.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.txtName.PasswordChar = '\0';
            this.txtName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtName.PlaceholderText = "Tên sản phẩm";
            this.txtName.ReadOnly = true;
            this.txtName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtName.SelectedText = "";
            this.txtName.SelectionLength = 0;
            this.txtName.SelectionStart = 0;
            this.txtName.ShortcutsEnabled = true;
            this.txtName.Size = new System.Drawing.Size(248, 41);
            this.txtName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtName.TabIndex = 0;
            this.txtName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtName.TextMarginBottom = 0;
            this.txtName.TextMarginLeft = 3;
            this.txtName.TextMarginTop = -3;
            this.txtName.TextPlaceholder = "Tên sản phẩm";
            this.txtName.UseSystemPasswordChar = false;
            this.txtName.WordWrap = true;
            // 
            // lblProductName
            // 
            this.lblProductName.AllowParentOverrides = false;
            this.lblProductName.AutoEllipsis = false;
            this.lblProductName.AutoSize = false;
            this.lblProductName.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblProductName.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblProductName.Font = new System.Drawing.Font("Readex Pro Deca", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblProductName.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.lblProductName.Location = new System.Drawing.Point(119, 278);
            this.lblProductName.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.lblProductName.Name = "lblProductName";
            this.lblProductName.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblProductName.Size = new System.Drawing.Size(119, 28);
            this.lblProductName.TabIndex = 1;
            this.lblProductName.Text = "Tên Sản phẩm";
            this.lblProductName.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblProductName.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblTitle
            // 
            this.lblTitle.AllowParentOverrides = false;
            this.lblTitle.AutoEllipsis = false;
            this.lblTitle.AutoSize = false;
            this.lblTitle.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblTitle.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblTitle.Font = new System.Drawing.Font("Readex Pro Deca", 27.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(29)))), ((int)(((byte)(34)))), ((int)(((byte)(40)))));
            this.lblTitle.Location = new System.Drawing.Point(475, 28);
            this.lblTitle.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblTitle.Size = new System.Drawing.Size(361, 80);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Đơn Bán Hàng";
            this.lblTitle.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.lblTitle.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = true;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // FrmOrder_Add
            // 
            this.AcceptButton = this.btnSave;
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(245)))), ((int)(((byte)(245)))), ((int)(((byte)(245)))));
            this.CancelButton = this.btnCancel;
            this.ClientSize = new System.Drawing.Size(1315, 726);
            this.Controls.Add(this.pnlMain);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "FrmOrder_Add";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Add / Edit Product";
            this.Load += new System.EventHandler(this.HienThiThongTInSKU_Load);
            this.pnlMain.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuPanel pnlMain;
        private Bunifu.UI.WinForms.BunifuLabel lblTitle;
        private Bunifu.UI.WinForms.BunifuLabel lblProductName;
        private Bunifu.UI.WinForms.BunifuTextBox txtName;
        private Bunifu.UI.WinForms.BunifuLabel lblSKU;
        private Bunifu.UI.WinForms.BunifuTextBox txtSKU;
        private Bunifu.UI.WinForms.BunifuLabel lblPrice;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCancel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.Framework.UI.BunifuDragControl bunifuDragControl1;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuLabel COGs;
        private Bunifu.UI.WinForms.BunifuTextBox numImportCost;
        private Bunifu.UI.WinForms.BunifuTextBox numPrice;
        private Bunifu.UI.WinForms.BunifuLabel Status;
        private Bunifu.UI.WinForms.BunifuTextBox txtTrangThaiSanPham;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnHienThi;
        private Bunifu.UI.WinForms.BunifuLabel lblStockInfo;
        private Bunifu.UI.WinForms.BunifuTextBox txtOrderID;
        private Bunifu.UI.WinForms.BunifuTextBox txtSoLuong;
    }
}